# interface customizations
- name: Customize interface config
  lineinfile:
    path: "{{jitsi_meet_interface_config}}"
    backrefs: yes
    regexp: '^(.\s*){{item.key}}:'
    line: '\1{{item.key}}: {{item.value}},'
  with_items: "{{ jitsi_meet_customizations }}"
  notify:
    - restart jitsi-videobridge

- name: Replace watermark for a customized one
  copy:
    src: "{{ jitsi_meet_watermark_file }}"
    dest: /usr/share/jitsi-meet/images/watermark.png
    owner: root
    group: root
    mode: "0644"
  when: jitsi_meet_watermark_file is defined
    and jitsi_meet_watermark_file is file

- name: Replace logo for a customized one
  copy:
    src: "{{ jitsi_meet_logo_file }}"
    dest: /usr/share/jitsi-meet/images/jitsilogo.png
    owner: root
    group: root
    mode: "0644"
  when: jitsi_meet_logo_file is defined
    and jitsi_meet_logo_file is file

- name: Replace favicon for a customized one
  copy:
    src: "{{ jitsi_meet_favicon_file }}"
    dest: /usr/share/jitsi-meet/images/favicon.ico
    owner: root
    group: root
    mode: "0644"
  when: jitsi_meet_favicon_file is defined
    and jitsi_meet_favicon_file is file

- name: Install custom body page template
  copy:
    src: "{{ jitsi_meet_body_template }}"
    dest: /usr/share/jitsi-meet/body.html
  when: jitsi_meet_body_template is defined
    and jitsi_meet_body_template is file

- name: Install custom head template
  copy:
    src: "{{ jitsi_meet_head_template }}"
    dest: /usr/share/jitsi-meet/plugin.head.html
  when: jitsi_meet_head_template is defined
    and jitsi_meet_head_template is file
