---
- import_tasks: install.yml
  tags: installation

- import_tasks: ufw.yml
  when: jitsi_meet_configure_firewall == true
  tags: firewall

- import_tasks: authentication.yml
  tags: authentication

- import_tasks: configuration.yml
  tags: configuration

- import_tasks: customization.yml
  when: jitsi_meet_customize_the_ui
  tags: customization
